### ISSUE TITLE
Increase text size / zoom level

### ISSUE THREAD

**Issue by nullxone** [grafbase/pathfinder#131]
Default text size is too small to use comfortably.

I would like to increase/set the text size throughout the whole interface; preferably with ctrl + / ctrl - keys (cmd + / cmd -).

**Comment by jonathanawesome** [comment]
Thanks for the report. This works for our React component _in the browser_, will need to do some research to figure out how to emulate in the desktop app.

**Comment by jonathanawesome** [comment]
Did a bit of looking and it turns out there's an [open `tauri-app` issue](https://github.com/tauri-apps/tauri/issues/3310) for this functionality. Until this is default for Tauri, we won't be scheduling time to implement it specifically. 

We released a new version (#168) with a larger font size for most type, which helps out our internal implementation and, I hope, helps with your usage of the desktop app.

We're not currently scheduling internal time to create a settings pane or other UI widget to toggle the font size, but we have it in the backlog. Happily accepting design ideas and/or PRs to address the issue.
